import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { RideProvider } from "@/contexts/RideContext";
import { Toaster } from "@/components/ui/toaster";
import { ChatProvider } from "@/contexts/ChatContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[url(/bg.webp)] min-h-screen w-screen bg-cover">

            <div className="bg-[#00000058] min-h-screen w-screen flex justify-center items-center">
                <RideProvider>
                  <ChatProvider>
                    <main className="w-full py-3">
                        {children}
                    </main>
                    <Toaster />
                  </ChatProvider>
                </RideProvider>
            </div>
        </div>
        
      </body>
    </html>
  );
}
